"use client";

import { useState } from "react";
import type { Audience } from "@/lib/types";

export interface AudienceCommentary {
  audience: Audience;
  commentary: string;
  metrics_cited: string[];
  management_attributions: string[];
  model: string;
  grounding: { metrics_available: number; transcript_chars: number };
}

/**
 * AI-generated commentary, grounded in exactly two sources: the computed
 * metrics (pipeline/metrics.py, deterministic Python) and management's own
 * half-year results transcript. Never the raw source PDFs - the model
 * narrates numbers Python already verified, it does not compute or reason
 * over the filings itself.
 *
 * The "Grounding" disclosure exists because a commentary card that reads like
 * confident prose invites the same blind trust a bare metric card would - the
 * whole point of this report is that a reader can check, so this card carries
 * its own check: which metric ids it actually cited, verified server-side
 * against the metrics it was given (see pipeline/commentary.py).
 */
export function CommentaryCard({
  commentary,
  onInspectMetric,
}: {
  commentary: AudienceCommentary | undefined;
  onInspectMetric: (metricId: string) => void;
}) {
  const [showGrounding, setShowGrounding] = useState(false);

  if (!commentary) {
    return (
      <div className="rounded-xl border border-dashed border-[var(--hairline)] bg-[var(--chip)] p-5">
        <h2 className="font-display text-base font-semibold tracking-tight text-[var(--brand-deep)]">
          AI commentary
        </h2>
        <p className="mt-2 text-sm text-[var(--muted)]">
          Not generated for this audience yet - the offline commentary run
          requires Anthropic API credit. Run{" "}
          <code className="rounded bg-[var(--surface)] px-1.5 py-0.5 font-mono text-xs">
            python -m pipeline.commentary
          </code>{" "}
          once credit is available. Every other figure in this report is
          unaffected - it is computed by deterministic code, not this feature.
        </p>
      </div>
    );
  }

  return (
    <div className="rounded-xl border border-[var(--hairline)] bg-[var(--surface)] p-5 shadow-[0_1px_2px_rgba(16,33,29,0.05)]">
      <div className="flex items-center justify-between gap-3">
        <h2 className="font-display text-base font-semibold tracking-tight text-[var(--brand-deep)]">
          AI commentary
        </h2>
        <button
          type="button"
          onClick={() => setShowGrounding((v) => !v)}
          className="text-xs font-medium text-[var(--accent-strong)] hover:underline"
        >
          {showGrounding ? "Hide grounding" : "Show grounding"}
        </button>
      </div>

      <p className="mt-3 text-[15px] leading-relaxed">{commentary.commentary}</p>

      {commentary.metrics_cited.length > 0 && (
        <div className="mt-4 flex flex-wrap gap-1.5">
          {commentary.metrics_cited.map((id) => (
            <button
              key={id}
              type="button"
              onClick={() => onInspectMetric(id)}
              className="rounded-full bg-[var(--chip)] px-2.5 py-1 text-[11px] font-medium
                         text-[var(--muted)] transition hover:bg-[var(--accent)]
                         hover:text-white"
            >
              {id.replace(/_/g, " ")}
            </button>
          ))}
        </div>
      )}

      {showGrounding && (
        <div className="mt-4 space-y-2 rounded-lg bg-[var(--chip)] p-3 text-xs leading-relaxed text-[var(--muted)]">
          <p>
            Generated by <span className="font-mono">{commentary.model}</span> from{" "}
            {commentary.grounding.metrics_available} computed metrics and an excerpt
            of the management results-presentation transcript. The model was
            never given the raw source PDFs and never asked to calculate
            anything - every figure it cites was computed by deterministic
            Python beforehand, and every citation above was checked against the
            metrics actually supplied before this card was built.
          </p>
          {commentary.management_attributions.length > 0 && (
            <p>
              <strong>Attributed to management, not verified independently:</strong>{" "}
              {commentary.management_attributions.join("; ")}
            </p>
          )}
        </div>
      )}
    </div>
  );
}
